### ISSUE TITLE
Version 0.2.0 breaks  kubernetes-cd plugin

### ISSUE THREAD

**Issue by ghost** [jenkinsci/azure-commons-plugin#18]
I installed the 0.2.0 update and after that the kubernetes-cd plugin was no longer able to load in Jenkins.

Except from Jenkins log attached
[log.txt](https://github.com/jenkinsci/azure-commons-plugin/files/1579565/log.txt)

**Comment by TonyLovesDevOps** [comment]
+1

**Comment by TonyLovesDevOps** [comment]
@LGDoor should the fixes in `0.2.1` or `0.2.2` fix this? Thanks in advance!

**Comment by LGDoor** [comment]
@tonyflint @n635998  0.2.2 should fix this issue. Tell me if it still doesn't work.

**Comment by TonyLovesDevOps** [comment]
@LGDoor I tried `0.2.2` and didn't run into this bug. Thank you! @n635998 I think this can be closed, pending your testing?
