### ISSUE TITLE
Typo in PROP_JENKINS_INSTAMCE_ID constant in AppInsightsConstants

### ISSUE THREAD

**Issue by darxriggs** [jenkinsci/azure-commons-plugin#29]
https://github.com/jenkinsci/azure-commons-plugin/blob/085187342cb2bae0d598498b134226d06ced31a0/azure-commons-plugin/src/main/java/com/microsoft/jenkins/azurecommons/telemetry/AppInsightsConstants.java#L15

**Comment by gavinfish** [comment]
@darxriggs please feel free to make a PR.
